
# GitHub 授权信息

github:
  client:
    id: 14ce1bdacd596e4269ba
    secret: 30fb52671490e80880ee6d7de6cdcc7c6215781c
  redirect:
    uri: http://localhost:8080/callback


# mysql 数据库
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coummity?serverTimezone=UTC
    username: root
    password: 123456