
# GitHub 授权信息
github:
  client:
    id: 14ce1bdacd596e4269ba
    secret: 6bf31ab8210472bfe8e9f85b121563895a745ec8
  redirect:
    uri: http://localhost:8887/callback


# mysql 数据库
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coummity?serverTimezone=UTC
    username: root
    password: 123456
  thymeleaf:
    cache: false

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.gyy.community.mapper
  mapper-locations: classpath:mapper/*.xml

#  启动端口
server:
  port: 8887

# 日志
logging:
  file:
    max-size: 1KB
    path: logs
  level:
    root: info
    com:
      gyy:
        community:
          mapper: debug
