
# GitHub 授权信息
github:
  client:
    id: 14ce1bdacd596e4269ba
    secret: c3fdc132b936ef8363d8ad778b26f05a37e87cc8
  redirect:
    uri: http://localhost:8080/callback


# mysql 数据库
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coummity?serverTimezone=UTC
    username: root
    password: 123456

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.gyy.community.mapper
  mapper-locations: classpath:mapper/*.xml
