
# GitHub 授权信息

github:
  client:
    id: 14ce1bdacd596e4269ba
    secret: 2e153f2c0d6ba746cd98830a12cd84b65bf7ef91
  redirect:
    uri: http://localhost:8080/callback


# mysql 数据库
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coummity?serverTimezone=UTC
    username: root
    password: 123456