
# GitHub 授权信息
github:
  client:
    id: 14ce1bdacd596e4269ba
    secret: 9169ad20d0cb2518f3b1ad3fbbd28fc09ad12e9e
  redirect:
    uri: http://localhost:8080/callback


# mysql 数据库
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coummity?serverTimezone=UTC
    username: root
    password: 123456

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true

